### ISSUE TITLE
Create Lite version with only topical headings (no qualifiers)

### ISSUE THREAD

**Issue by marijane** [galterlibrary/invenio-subjects-mesh#12]
**Environment:** Invenio v9.1

**Problem:** It is not possible to select MeSH terms that are both headings and subheadings, for example, Blood, Cytology, or Genetics

**Steps to Reproduce:**

1. Set up InvenioRDM and install invenio-subjects-mesh
2. Log in and start a new upload
3. In the 'Search for a subject by name' box, type 'blood' or 'cytology' or 'genetics'

**Results:**

- The autocomplete dropdown populates with MeSH headings that use the blood, cytology, or genetics subheadings. 
- The list of heading suggestions in the list begin with the letter "H"; the sort order is non-obvious.
- The length of the drop-down is limited, so the main headings for these words never appear and therefore cannot be selected and added to a record.
- These headings can only be found if you type at least four letters of an allowable subheading for the main headings; the main headings cannot be used as standalone headings.

**Expected Results:**
Main headings should appear first in the drop down, before any use as subheadings. This seems like an index weighting issue.

**Suggestions:**
Subheadings should perhaps not appear at all. Please consider releasing a version of this vocabulary that only includes main headings. There are ~30,000 MeSH headings, which is plenty for many users' needs,  and the inclusion of heading-subheading pairs blows that up to something like ~650,000 terms, which seems excessive and requires more expertise to apply correctly.

**Comment by fenekku** [comment]
Hi @marijane thanks for the report!

So yes, most of the display issue has to do with weighting on the suggestions. This is something that plagues other autocompletes in InvenioRDM: especially getting "English" as the first recommendation for "eng". I think a wider effort on that would solve the problem for different subjects. Just being able to pass a weight in the fixtures would probably be enough, so not the biggest lift.

Having a listing of only the top-level MeSH headings would indeed be good and I can eventually work on that. Either as an extra or as an alternate repo, that should be straightforward. I will mark this as something for our next sprint at Northwestern (probably taken up in September if no other superseding priorities).     

Thanks!

**Comment by fenekku** [comment]
@marijane Sorry about the delay - we had other priorities, then I refactored and modernized most of our subject packages. All that is done and it should now be possible to use: https://pypi.org/project/invenio-subjects-mesh-lite/ instead of this repo to get MeSH topical subject terms without qualifiers. In turn, that should help with seeing more relevant autocomplete results barring any improvements on that side from the main InvenioRDM modules.

Enjoy!

**Comment by marijane** [comment]
@fenekku Question: how do we uninstall the old mesh subjects so we can use the new lite version?

**Comment by fenekku** [comment]
### Main steps
The steps for this are still manual but eventually there should be a programmatic way from the main modules. Essentially you will want to do the following in a test environment first and then on your production setup:

0- Check if existing records have been using MeSH terms with qualifiers and remedy those records (perhaps take note of records to revisit after transition)
1- Delete MeSH subjects from your document engine (Elasticsearch / Opensearch)
2- Delete MeSH subjects from your database
3- Uninstall invenio-subjects-mesh (`pipenv uninstall invenio-subjects-mesh`)
4- Install invenio-subjects-mesh-lite (`pipenv install invenio-subjects-mesh-lite`)
5- Rerun fixture loading (will pick up this change and only load the mesh-lite terms): `pipenv run invenio rdm-records fixtures`
6- Do any metadata enhancement remedial noted down from step 0 

*Step 1 - Deleting a subject in document engine in more details*

```bash
# add your credentials and such...
curl -XPOST {{your opensearch hostname}}/subjects-subject-v1.0.0/_delete_by_query?conflicts=proceed&pretty -d '
```
```json
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "scheme": "MeSH"
        }
      }
    }
  }
}
```
```
'
```

*Step 2 - Deleting a subject in database in more details*

```sql
DELETE
    FROM pidstore_pid
    WHERE pid_value LIKE 'https://id.nlm.nih.gov/mesh/%';

DELETE
    FROM subject_metadata
    WHERE json::json->>'scheme' = 'MeSH';

DELETE
    FROM vocabularies_schemes
    WHERE id = 'MeSH';
```

This should be it, good luck!

**Comment by monotasker** [comment]
Created PR to address the problem by changing default query type form "bool_prefix" to "best_fields": https://github.com/inveniosoftware/invenio-records-resources/pull/552
